# Generated by Django 5.1.1 on 2024-09-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
