# Generated by Django 5.1.1 on 2024-09-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bookmark_bookmarklist_delete_bookmarklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='BookmarkList',
            new_name='user',
        ),
    ]
